### PR TITLE
Added option for repeating head in print.

### PR DESCRIPTION
**Pull request by aravindnc**
Added a new option for printing so that people can now repeat their page heading and custom image to every page while printing. Previously this was applicable to first page only.

Below are new options,
```
repeatingHead: {
logo: 'http://example.com/logo.png',
logoPosition: 'right', //left, right, center
logoStyle: 'padding-bottom:5px', 
title: '<h3>Sample Heading</h3>'
}
```

### CODE REVIEW

**Comment by aravindnc** [comment]
@DataTables Thanks for your reply.

Yes, the browser is repeating the thead element to the multiple pages while printing. I've added it as a separate setting so that it won't mess with other options.

**Comment by aravindnc** [comment]
@DataTables  Can this be merged to the main repo as it has been used by multiple users.

**Comment by AllanJard** [comment]
We haven't really seen much demand for it, but it is a nice idea. It is something we'll look at bringing into Buttons in future.

**Comment by aravindnc** [comment]
Thanks.

**Pull request closed without merging**
