### PR TITLE
Add clickBlurs parameter to prevent blurring on specific buttons

### PR DESCRIPTION
**Pull request by tharglet**
Discussion: https://datatables.net/forums/discussion/51832/feature-to-prevent-blur-on-button-click/

Done in the simplest way possible, with preserving the current default behaviour. 
(If there's guidelines of how invalidish input should be handled i.e. if clickBlurs is not a boolean, let me know so I can modify the PR to incorporate the system required).

### CODE REVIEW

**Comment by DataTables** [comment]
The looks good to me - thanks. Although does `config.clickBlurs == null` not been to be `config.clickBlurs === undefined` since it won't be `null`?

Are you happy for this to be included under the MIT license?

**Comment by tharglet** [comment]
== null traps both null and undefined. I can change it to undefined if you prefer? Happy for it to be included under MIT license.

**Comment by DataTables** [comment]
Yes please, that would be great. A strict check would be good there - I try to use it throughout the code base (unless there is a good reason not to).

**Comment by DataTables** [comment]
Awesome - thank you for this!

**Pull request merged**
