### PR TITLE
Fix an error when there is no buttons config

### PR DESCRIPTION
**Pull request by tfermm**
Fixes an error if the DataTables "dom" has the property for Buttons but there are no buttons config defined.

### CODE REVIEW

**Comment by DataTables** [comment]
Thanks for this! I think I'd prefer it to be `config = {}` rather than an array since the configuration is expected to be an object. But other than that it looks like a very useful addition.

Happy to make the update myself, or for the PR to be updated as you prefer?

Are you happy for this to be included under the MIT license?

**Comment by tfermm** [comment]
I first tried setting `config = {};` when I did that it made all of the buttons show up instead of none of the buttons. I believe it should stay as `config = [];`.

I am good with it being under the MIT license.

**Comment by DataTables** [comment]
Actually, I would say that if there is no configuration provided then the defaults should be used, which is what is happening when it is an object.

**Comment by tfermm** [comment]
Okay fair enough.

**Comment by DataTables** [comment]
Thanks!

**Pull request merged**
