### PR TITLE
Fix XSS in print page

### PR DESCRIPTION
**Pull request by dev**
https://i.imgur.com/gsChT5D.png
When clicking print button: https://i.imgur.com/fH3pc06.png

### CODE REVIEW

**Comment by DataTables** [comment]
Good point! But does this allow HTML still to be written into the page, which is a valid use case.

**Comment by legit** [comment]
Oh, are people supposed to be able to execute HTML here? Didn't know that, sorry. 
If that's the case, we shouldn't replace < and > but we should replace <script>, <svg..>, <* onerror=".."> etc

**Comment by DataTables** [comment]
What would be ideal is for an HTML reader to get the entities shown in the first cell in your example as encoded entities. That way the print view would appear in an identical way.

**Comment by legit** [comment]
I don't really understand what you mean, sorry :[

**Comment by DataTables** [comment]
I'm finally up to speed with this one - sorry for the delay. It was being caused by the `decodeEntities` option. That is useful for PDF, copy and Excel output, but it introduces a possible XSS vector for the print view. I've fixed it now by disabling decodeEntities for print view.

The error could be reproduced in any of the print examples using:

```js
$('#example').DataTable().clear();
$('#example').DataTable().row.add(['&lt;b&gt;hello&lt;/b&gt;','<b>World</b>',2,3,4,5]).draw()
```

Thanks again for bringing this up!

**Pull request closed without merging**
