### PR TITLE
Load custom scripts in print page

### PR DESCRIPTION
**Pull request by petermorlion**
## Context

I was looking for a way to add page numbers to the output of the `print` button.

## Analysis

Browsers currently don't fully support the [@page](https://developer.mozilla.org/en-US/docs/Web/CSS/@page) CSS rule and its possible children ([margin at-rules](https://developer.mozilla.org/en-US/docs/Web/CSS/@page#margin_at-rules), [counter](https://developer.mozilla.org/en-US/docs/Web/CSS/counter) etc).

Luckily, there is a polyfill script called [PagedJS](https://pagedjs.org/). To be able to use this, we need to be able to add the script to the window that opens when we click the print button. Additionally, the script must be executed so PagedJS can do its work.

Adding PagedJS hard-coded wouldn't be a nice solution. Being able to add scripts dynamically, whatever the script, seems like a more extensible solution.

## Solution

I added the possibility of adding a `customScripts` array. If you add URLs of JS files, they will be added to the print window. To do so, I create a `script` tag dynamically and add it to the head:

```
if (config.customScripts) {
	config.customScripts.forEach(function (script) {
		var tag = win.document.createElement("script");
		tag.src = script;
		win.document.getElementsByTagName("head")[0].appendChild(tag);
	});
}
```

We can't just append to the `head` variable (a string) that is being built, because then it doesn't seem to work (possibly because the HTML has already been parsed).

## Example

I built a [Codepen example](https://codepen.io/petermorlion/pen/qBwGEpQ). I load the existing Datatables JS but overwrite the `DataTable.ext.buttons.print` function. Bascially, I pasted there what is in the pull request.

I also added page numbering to the CSS.

If you click the print button, you'll see there are now pagenumbers.

### CODE REVIEW

**Comment by AllanJard** [comment]
Great pull request - thank you. Are you happy for this to be included under the MIT license?

**Comment by petermorlion** [comment]
@AllanJard yes, no problem!

**Comment by AllanJard** [comment]
Awesome - thank you!

I notice that it doesn't appear to work in Firefox, but does in Chrome. Is that expected? Possibly the polyfill needs something Firefox doesn't provide?

**Comment by petermorlion** [comment]
Oh, I didn't test on Firefox, because I don't have it installed. I'll take a look. Though I won't have time next week, so it might take a while.

**Comment by petermorlion** [comment]
@AllanJard is it the Codepen example that doesn't work in FF? Because that seems to work on my machine (hate to use that phrase).

**Comment by AllanJard** [comment]
It was the example that I recall I was having issues with, but I've just tried again and it seems to work fine, so possibly I forgot to clear the cache. Sorry about that! It's working grand. Thanks again for adding this!

**Pull request merged**
