### PR TITLE
New: Add `buttons.config.sheetName` option to give the ability to set…

### PR DESCRIPTION
**Pull request by pitervergara**
… sheet name on '.xlsx' export.

Regarding this discussion http://datatables.net/forums/discussion/comment/86598#Comment_86598
that's how I managed to make the change in the sheet name.

Here is an example of usage: http://live.datatables.net/luwaceca/9/edit

I'm not sure where is the best point to insert that logic, so I inserted it just before the file generation.

### CODE REVIEW

**Comment by DataTables** [comment]
Hi,

Thanks for this. I wonder if we might integrate it into the current setup using a regex replace rather than an XML parse (which I know is strictly correct, but also significantly more code).

We'd also need to do the same in the Flash part and add it to the documentation.

Happy to take over the change, or would be delighted if you update your PR with these changes :-)

**Comment by pitervergara** [comment]
Sure. I'll be glad to do it, after christmas. I'm not sure about the flash
part, but if I have difficulties with this, I'll ask for help;


Em 21/12/2015 3:06 PM, "Allan Jardine" <notifications@github.com> escreveu:

**Comment by pitervergara** [comment]
Hi!

I submitted some changes to implement your sugestions. 

I had some trouble with the flex sdk, so I've used a version different of the suggested inside the ZeroClipboard.as file (I've used 4.14). AFAIK I didn't broke anything because of that, but even so I made a specific commit for the compiled swf file, so you may discard it.

I could not do a publicly available working example for the excelFlash (I suppose some policy is preventing it to be linked from github). But in my local server it looked ok.

This are my attempts to demonstrate the implemetation:
http://codepen.io/pitervergara/pen/JGbwbw  (flash - not working on codepen)
http://codepen.io/pitervergara/pen/xZRmZy (html5 - working on codepen)

hope it's useful;

**Comment by DataTables** [comment]
Absolutely - awesome. Thanks for this! Are you happy for this to be released under the MIT license?

**Comment by pitervergara** [comment]
you are welcome! I am happy to give something back to such a useful project. I agree with the licensing.

**Comment by DataTables** [comment]
Super - thanks very much!

**Pull request merged**
