### PR TITLE
Make excelFlash export work with IE8

### PR DESCRIPTION
**Pull request by Worthy7**
Can't believe I managed to fix this...

### CODE REVIEW

**Comment by DataTables** [comment]
That looks superb - very clever.

I need to reinstall an IE8 VM and test it out, but that does look good. The one thing I'm not sure about is that the try/catch is more or less never going to fail now (since any errors from the `.xml` property are going to come later on when that function is used. But then, if this works in IE8, there probably isn't any need to do a try/catch at all.

**Comment by Worthy7** [comment]
I didn't put it there lol

**Comment by Worthy7** [comment]
This breaks IE10 because its not "strict" compliant.

**Comment by DataTables** [comment]
Good info - thanks. I'll look into that aspect when I'm able to look into it in a bit more detail.

**Comment by Worthy7** [comment]
There you go - had to fix this for work anyway.

**Comment by DataTables** [comment]
I think this is looking good - thanks!

Are you happy for this to be included under the MIT license?

**Comment by Worthy7** [comment]
Yea of course.

**Pull request merged**
