### PR TITLE
[WIP] Multi-row head export

### PR DESCRIPTION
**Pull request by Ladel**
Hi,

Status: WIP (work in process).
TODO:
- [ ] Implementation of colspan
- [ ] Implementation of rowspan

Best regards,

### CODE REVIEW

**Comment by DataTables** [comment]
Thanks for sending the PR. There are a few gotcha's with multi-row headers and footers (colspan / rowspan just can't be supported in CSV for example) so I'm not going to pull this in immediately. I'll review closely and hopefully pull it in in the not to distant future.

**Comment by Ladel** [comment]
Hi, @DataTables 

This is just an outline. I will continue to completion.
I created this PR in order to support the community with advice.

Best regards,

**Comment by Ladel** [comment]
Status: WIP (work in process).

**Comment by RaufAli** [comment]
Hi @Ladel! 

Thanks for solution, it was useful =)

**Comment by cat0rgi0** [comment]
@DataTables  I think for CSV usually rows of header isn't necessary .

**Comment by exbarboss** [comment]
Is there any plans to include multiple headers export feature in upcoming releases?

**Comment by DataTables** [comment]
Yes, but I'm not sure when. It isn't planned in the near future I'm afraid.

**Comment by lidinsky** [comment]
Hi, @DataTables

May I ask if this feature could be implemented? Thank you for answer. Good work!

**Comment by DataTables** [comment]
It hasn't yet I'm afraid. It is something I'm aware of needing to be done, but I want to change the framework of how it works in DataTables core first.

**Comment by DataTables** [comment]
Hi! So there are a number of things that need to be addressed as part of the work for multi-row header and footer export, some of which are not trivial unfortunately:

* How to handle column visibility. DataTables does not expose multi-row header / footer elements via an API. That's going to need a chance in DataTables core.
* DataTables column visibility doesn't handle colspan / rowspan very well yet.
* Does pdfmake support colspan / rowspan? I've not looked into that yet
* Backwards compatibility - the export API explicitly uses single rows at the moment, so this would need to be a major release breaking backwards compatibility.

1 and 2 are actually at least in part addressed in the v2 branch of DataTables. So my intention is to finish exposing that information via the API and then have a branch of Buttons that supports those new features until DT2 alpha / beta is ready.

The trick there is that I don't have a time scale for that yet as I'm working on a number of other things as well.

**Comment by mtyszler** [comment]
Tks @DataTables for the quick reaction.

Let me highlight a bit what my solution (within R) handles, so you can assess a bit better. First of all, I just want to highlight that my solution was aiming at complex headers, but not complex footers.

Take this table as initial example (this is generated within a R Shiny application):
image


> * How to handle column visibility. DataTables does not expose multi-row header / footer elements via an API. That's going to need a chance in DataTables core.

Indeed this was an issue. The initial solution sketched was missing the mark when colvis was active, or columns where programmatically hidden. This [commit](https://github.com/mtyszler/DT/commit/890094de7ba4782d53a795eb595188c1eaed8060) specifically handles that. 

From my example table above, regardless of the column visibility on screen, the full table is exported, unless specified by code by the programmer (which also works fine).  Of course we could test it further to make sure I didn't miss any special case.

> * DataTables column visibility doesn't handle colspan / rowspan very well yet.

I'm not sure I know what you mean here. I have no problems with that. I didn't try extensively with hiding columns by code, but the few trials I had showed me no problem.

> * Does pdfmake support colspan / rowspan? I've not looked into that yet

So far, copy, print, csv and pdf (i.e., everything except excel) handles in the same way, which is having "empty"  columns for the spanned cols or rows. For example, the pdf export is: 
[pdf_example_export.pdf](https://github.com/DataTables/Buttons/files/4099801/pdf_example_export.pdf) and the csv export is 
image

Excel export does merge the cells: 
[excel_example_export1.xlsx](https://github.com/DataTables/Buttons/files/4099926/excel_example_export1.xlsx)



> * Backwards compatibility - the export API explicitly uses single rows at the moment, so this would need to be a major release breaking backwards compatibility.

I don't see a problem here. See this [base commit](https://github.com/rstudio/DT/pull/751/commits/ed15f2f9335cfe2b314091ac29980311fb0c2345) where the single-row header is replaced by a headerMatrix. Subsequently, the export functions for example [here](https://github.com/mtyszler/DT/commit/ae44b9e4247974f7417858de07bd365271e336b8) and [here](https://github.com/mtyszler/DT/commit/8e9357c621a9638278cf940b296157043b8fbb91) were updated to handle multi-row headers. In that sense, the single-row case becomes a special case. 

> 1 and 2 are actually at least in part addressed in the v2 branch of DataTables. So my intention is to finish exposing that information via the API and then have a branch of Buttons that supports those new features until DT2 alpha / beta is ready.

See if my suggestions help here.

> The trick there is that I don't have a time scale for that yet as I'm working on a number of other things as well.

I'm very interested in having this feature mainstreamed. I think @yihui and @shrektan would also appreciated it. At the moment I'm using my own [fork](https://github.com/mtyszler/DT/), but of course I'd prefer to use the main version.

Therefore if you'd be open to me "translating" my solution to here, I can try to find the time to do so.
If you prefer to check my solution and judge if it is helpful, also fine. Just let me know.

**Comment by DataTables** [comment]
> > Backwards compatibility
> I don't see a problem here.

The API is changing - `buttons.exportData()` will no longer have a 1D array for the header and footer, but rather will have a 2D array. It's not a major issue, but it is a change in the API so it would need a Buttons 2 release.

The changes do look useful and it looks feature complete since you are using the internal aoHeader option. I'd like to see the same applied to the footer, but I could potentially add that if needed.

**Comment by marcelod** [comment]
I look forward to this feature

**Pull request closed without merging**
