### PR TITLE
Extend stripHtml RegExp to cover quoted attributes

### LINKED ISSUE #176: `stripHtml` option fails when attribute contains `>` symbol
In our use case, we're using DataTables in conjunction with [Stimulus.js](https://stimulusjs.org/) to provide additional data interactivity. Stimulus uses the HTML5 `data-` attribute to specify actions in the form [`event->controller#method`](https://stimulusjs.org/reference/actions).

After integrating Stimulus we discovered that our exported data contains fragments of HTML despite the `stripHtml` option set.

I've tracked the bug down to this relatively simplistic RegExp:

https://github.com/DataTables/Buttons/blob/d7bececf07a22cb8cf686f965bb5f8363a2bfc13/js/dataTables.buttons.js#L2026-L2028

This RegExp does not cover the case where an HTML tag contains `>` within an attribute.

One option is to extend the RegExp to cover quoted attributes, ie
```
/<([^>'"]*('[^']*'|"[^"]*")?)*>/g
```

However I'm also curious if there is a good reason you do not simply use the `HTMLElement.textContent` property instead of `HTMLElement.innerHTML` when `stripHtml` is specified. This would let the browser take care of all the HTML parsing concerns, rather than trying approximate it with RegExp.

Open to hear your thoughts. Thanks for your time and hard work, and let me know if you'd like a PR for this.

### PR DESCRIPTION
**Pull request by kueblc**
Fixes #176

### CODE REVIEW

**Comment by kueblc** [comment]
I hereby release this contribution under the project's MIT license

**Comment by DataTables** [comment]
Awesome - thank you.

**Comment by kueblc** [comment]
Glad to help, and thank you for merging this quickly. May I ask when I can expect this fix to reach npm?

**Comment by DataTables** [comment]
I'm hoping it will be within the next couple of weeks. That's the plan anyway :-). We've got a few releases to tag up and release.

**Comment by kueblc** [comment]
As this is an issue that is actively affecting our customers during a critical time of our business year, we're looking into building this locally until the patch hits distribution.

I looked into your `make.sh` and saw some tools I do not recognize; `css_frameworks`, `js_frameworks`, `js_compress`, `examples_process`. A search didn't turn up any useful information. Are these tools available somewhere?

Appreciate the help! Thanks again.

**Comment by DataTables** [comment]
The change is in the [nightly build that we host](https://datatables.net/download/nightly#Buttons).

If you want to build the software yourself, you need the [DataTablesSrc repo](/DataTables/DataTablesSrc) which contains those bash functions. I thought we had a blog post about building the software, but apparently not. We'll get that done.

**Comment by DataTables** [comment]
Ah - [here we go](https://datatables.net/manual/development/build) - I knew we had some docs about it somewhere. We've got a VM that can be used to install all required tools as well - that we do still need to document.

**Pull request merged**
